// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC__WOgBCyRsZIna7OEBetgFbBUGJnvaWw',
    appId: '1:154768656057:web:a57b0f3a19322aafe37d68',
    messagingSenderId: '154768656057',
    projectId: 'iotproject-cb7b7',
    authDomain: 'iotproject-cb7b7.firebaseapp.com',
    databaseURL: 'https://iotproject-cb7b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-cb7b7.firebasestorage.app',
    measurementId: 'G-BQ8S1RT7PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-D8FqxWYqw33tbG8WXTKwV-sFjZaLaIs',
    appId: '1:154768656057:android:dd0cc9c18958dbc1e37d68',
    messagingSenderId: '154768656057',
    projectId: 'iotproject-cb7b7',
    databaseURL: 'https://iotproject-cb7b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-cb7b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX7shRiUPLw_8oSCu5Drp_kkOYW3v5u3g',
    appId: '1:154768656057:ios:c201718ed2dbaee8e37d68',
    messagingSenderId: '154768656057',
    projectId: 'iotproject-cb7b7',
    databaseURL: 'https://iotproject-cb7b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-cb7b7.firebasestorage.app',
    iosBundleId: 'com.example.iotproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX7shRiUPLw_8oSCu5Drp_kkOYW3v5u3g',
    appId: '1:154768656057:ios:c201718ed2dbaee8e37d68',
    messagingSenderId: '154768656057',
    projectId: 'iotproject-cb7b7',
    databaseURL: 'https://iotproject-cb7b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-cb7b7.firebasestorage.app',
    iosBundleId: 'com.example.iotproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC__WOgBCyRsZIna7OEBetgFbBUGJnvaWw',
    appId: '1:154768656057:web:9648b37920f58d05e37d68',
    messagingSenderId: '154768656057',
    projectId: 'iotproject-cb7b7',
    authDomain: 'iotproject-cb7b7.firebaseapp.com',
    databaseURL: 'https://iotproject-cb7b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-cb7b7.firebasestorage.app',
    measurementId: 'G-73CCBE932Y',
  );
}
